export const stepContent = [
  {
    // 1
    label1: "Haber incurrido como mínimo en 2 infracciones de la disciplina laboral",
    value1: "1|2|M",
    label2: "Haber incurrido en 1 infracción de la disciplina laboral.",
    value2: "1|3|R",
    label3: "No ha cometido ninguna violación de la disciplina laboral.",
    value3: "1|4|B",
    label4: "Se destaca por su excelente disciplina",
    value4: "1|5|MB",
  },
  {
    // 2
    label1: "Contar con al menos una medida disciplinaria",
    value1: "2|2|M",
    label2: "No Procede",
    value2: "2|3|R",
    label3: "Haber incurrido en 1 infracción de la disciplina laboral",
    value3: "2|4|B",
    label4: "No ha sido objeto de ningún señalamiento",
    value4: "2|5|MB",
  },
  {
    // 3
    label1: "Se ausentó a las actividades del PPI.",
    value1: "3|2|M",
    label2: "Se ausentó a la guardia obrera.",
    value2: "3|3|R",
    label3: "Participa en todas las actividades del PPI.",
    value3: "3|4|B",
    label4: "Participa activamente en todas las actividades del PPI y la guardia obrera",
    value4: "3|5|MB",
  },
  {
    // 4
    label1: "Con tachaduras, borrones y al menos un error contable",
    value1: "4|2|M",
    label2: "Sin tachaduras y borrones pero al menos un error contable",
    value2: "4|3|R",
    label3: "Sin tachaduras, borrones y errores contables",
    value3: "4|4|B",
    label4: "Documentación primaria con excelente presentación y contenido",
    value4: "4|5|MB",
  },
  {
    // 5
    label1: "Detectadas al menos 2 deficiencias en los controles realizados",
    value1: "5|2|M",
    label2: "Detectada al menos 1 deficiencia en los controles realizados",
    value2: "5|3|R",
    label3: "No se le ha detectado ninguna deficiencia en los controles realizados",
    value3: "5|4|B",
    label4: "Con resultados satisfactorios en las operaciones de control realizadas",
    value4: "5|5|MB",
  },
  {
    // 6
    label1: "No es responsable en el cuidado y preservación de los recursos bajo su responsabilidad",
    value1: "6|2|M",
    label2: "No procede",
    value2: "6|3|R",
    label3: "Es responsable en el cuidado y preservación de los recursos bajo su responsabilidad",
    value3: "6|4|B",
    label4: "Se destaca por su responsabilidad y preservación de los recursos y bienes bajo su responsabilidad",
    value4: "6|5|MB",
  },
  {
    // 7
    label1: "Realiza las tareas propias de su puesto de trabajo con insuficiente calidad y resultados",
    value1: "7|2|M",
    label2: "En ocasiones algunas de las tareas correspondientes a su puesto de trabajo las realiza deficientemente",
    value2: "7|3|R",
    label3: "Realiza las tareas correspondientes a su puesto de trabajo",
    value3: "7|4|B",
    label4: "Se destaca por el desempeño de sus tareas, realizándolas eficazmente con rapidez, habilidad y un excelente nivel de calidad",
    value4: "7|5|MB",
  },
  {
    // 8
    label1: "Es indiferente a las tareas relacionadas con la calidad",
    value1: "8|2|D",
    label2: "Contribuye escasamente en las tareas del Programa de Calidad",
    value2: "8|3|R",
    label3: "Cumple con las tareas del Programa y se preocupa por la calidad del servicio que presta",
    value3: "8|4|B",
    label4: "Se destaca por su activa participación en el cumplimiento del Programa de Calidad y con los estándares establecidos",
    value4: "8|5|MB",
  },
  {
    // 9
    label1: "Se reciben al menos 2 quejas por parte de los clientes",
    value1: "9|2|M",
    label2: "Se recibe una queja por parte de los clientes",
    value2: "9|3|R",
    label3: "No se recibenquejas por parte de los clientes",
    value3: "9|4|B",
    label4: "No se reciben quejas, y sí reconocimientos o felicitaciones por parte de los clientes",
    value4: "9|5|MB",
  },
  {
    // 10
    label1: "Incumplimiento de los planes de ventas en 59% o menos",
    value1: "10|2|M",
    label2: "Cumplimiento de los planes de ventas entre el 60-85%",
    value2: "10|3|R",
    label3: "Cumplimiento de los planes de ventas entre el 85-100%",
    value3: "10|4|B",
    label4: "Sobrecumplimiento de los planes de ventas",
    value4: "10|5|MB",
  },
  {
    // 11
    label1: "Ante situaciones imprevistas no es capaz de reaccionar demostrando inseguridad",
    value1: "11|2|M",
    label2: "En ocasiones no reacciona correctamente ante situaciones imprevistas",
    value2: "11|3|R",
    label3: "Ante situaciones imprevistas reacciona rápidamente aportando iniciativas adecuadas",
    value3: "11|4|B",
    label4: "Se destaca por su gran capacidad de reacción ante situaciones imprevistas, tiene mucha iniciativa",
    value4: "11|5|MB",
  },
  {
    // 12
    label1: "Se demora excesivamente en la realización de sus funciones",
    value1: "12|2|M",
    label2: "Existe demora en ocasiones para realizar sus funciones",
    value2: "12|3|R",
    label3: "Realiza sus funciones con rapidez y agilidad",
    value3: "12|4|B",
    label4: "Se destaca por la rapidez y calidad con que ejecuta sus funciones",
    value4: "12|5|MB",
  },
  {
    // 13
    label1: "No promueve la venta de los servicios y opcionales",
    value1: "13|2|M",
    label2: "Promueve esporádicamente la venta de los servicios y opcionales",
    value2: "13|3|R",
    label3: "Promueve la venta de los servicios y opcionales",
    value3: "13|4|B",
    label4: "Promueve activamente los servicios y opcionales",
    value4: "13|5|MB",
  },
  {
    // 14
    label1: "Domina insuficientemente sus funciones para poder desempeñar su trabajo correctamente",
    value1: "14|2|M",
    label2: "Domina las funciones permitiéndole desarrollar su trabajo, pero carece de la profundidad necesaria para un correcto desempeño",
    value2: "14|3|R",
    label3: "Domina sus funciones permitiéndole desarrollar su trabajo correctamente",
    value3: "14|4|B",
    label4: "Se destaca por el excelente dominio de sus funciones para desarrollar su trabajo de forma sobresaliente",
    value4: "14|5|MB",
  },
  {
    // 15
    label1: "Posee insuficientes conocimientos técnicos profesionales para desarrollar su trabajo",
    value1: "15|2|M",
    label2: "Posee los conocimientos técnicos profesionales básicos para desempeñar su trabajo, pero carece de la profundidad necesaria para su correcto desempeño",
    value2: "15|3|R",
    label3: "Posee los conocimientos técnicos profesionales para desempeñar su trabajo correctamente",
    value3: "15|4|B",
    label4: "Se destaca por los amplios conocimientos técnicos profesionales que posee para un excelente desempeño de su trabajo",
    value4: "15|5|MB",
  },
  {
    // 16
    label1: "No es amable y cortés con el cliente",
    value1: "16|2|M",
    label2: "En ocasiones no se muestra amabe y cortés con os clientes",
    value2: "16|3|R",
    label3: "Atiende a los clientes con amabilidad y cortesía",
    value3: "16|4|B",
    label4: "Se destaca por su amabilidad y cortesía, ofreciéndole siempre una sonrisa al cliente",
    value4: "16|5|MB",
  },
  {
    // 17
    label1: "Usa indevidamente la infomación que maneja",
    value1: "17|2|M",
    label2: "No procede",
    value2: "17|3|R",
    label3: "Usa debidamente la información que maneja en su trabajo",
    value3: "17|4|B",
    label4: "Se destaca por el debido uso de información que maneja en su trabajo",
    value4: "17|5|MB",
  },
  {
    // 18
    label1: "No trabaja suficientemente en equipo, predominan sus intereses individuales, no colabora con los objetivos del colectivo",
    value1: "18|2|M",
    label2: "Colabora con los diferentes puestos y áreas pero predominan sus objetivos personales",
    value2: "18|3|R",
    label3: "Trabaja en equipo, participa activamente en los objetivos del colectivo",
    value3: "18|4|B",
    label4: "Se destaca por promover, desarrollar y apoyar la colaboración con los diferentes puestos y áreas asumiendo como propios los objetivos del colectivo",
    value4: "18|5|MB",
  },
  {
    // 19
    label1: "Incumple con las tareas que le son asignadas",
    value1: "19|2|M",
    label2: "En ocasiones incumple con las tareas que le son asignadas",
    value2: "19|3|R",
    label3: "Cumple de forma correcta las tareas que le son asignadas",
    value3: "19|4|B",
    label4: "Se destaca por el cumplimiento de las tareas que le son asignadas aplicando la iniciativa, rapidez y responsabilidad",
    value4: "19|5|MB",
  },
  {
    // 20
    label1: "Su puesto de trabajo está desorganizado y carece de higiene",
    value1: "20|2|M",
    label2: "En ocasiones su puesto de trabajo está desorganizado y la higiene es deficiente",
    value2: "20|3|R",
    label3: "Mantiene correcta higiene y organización del puesto de trabajo",
    value3: "20|4|B",
    label4: "Su puesto de trabajo se destaca por estar organizado y con una excelente higiene",
    value4: "20|5|MB",
  },
  {
    // 21
    label1: "Incumple las normas de seguridad y salud establecidas en su puesto de trabajo",
    value1: "21|2|M",
    label2: "En ocasiones incumple con las normas de seguridad y salud",
    value2: "21|3|R",
    label3: "Cumple con todas las normas de seguridad y salud",
    value3: "21|4|B",
    label4: "Se destaca por el cumplimiento correcto de las normas de seguridad y salud",
    value4: "21|5|MB",
  },
  {
    // 22
    label1: "No habla inglés y no se comunica como es debido con los clientes",
    value1: "22|2|M",
    label2: "Habla inglés con dificultad",
    value2: "22|3|R",
    label3: "Habla inglés fluido",
    value3: "22|4|B",
    label4: "Habla más de 2 idiomas",
    value4: "22|5|MB",
  },
  {
    // 23
    label1: "Aplica las guías de chequeo y cumple con el plan de higiene total diario del área en un 75% o menos",
    value1: "23|2|M",
    label2: "Aplica las guías de chequeo y cumple con el plan de higiene total diario del área en más de un 75%",
    value2: "23|3|R",
    label3: "Aplica las guías de chequeo y cumple con el plan de higiene total diario del área en más de un 85%",
    value3: "23|4|B",
    label4: "Aplica las guías de chequeo y cumple con el plan de higiene total diario del área en más de un 95%",
    value4: "23|5|MB",
  },
  {
    // 24
    label1: "Ausencias justificadas reiteradas",
    value1: "24|2|M",
    label2: "Ha tenido más de una llegada tarde",
    value2: "24|3|R",
    label3: "No ha tenido ausencias, pero ha llegado tarde una vez",
    value3: "24|4|B",
    label4: "No tiene ausencias y siempre es puntual",
    value4: "24|5|MB",
  },
  {
    // 24
    label1: "Uso incorrecto del uniforme reiterado",
    value1: "25|2|M",
    label2: "Haber sido requerido por su jefe al menos una vez por el uso incorrecto del uniforme",
    value2: "25|3|R",
    label3: "Usa correctamente el uniforme",
    value3: "25|4|B",
    label4: "Se destaca por su presencia personal",
    value4: "25|5|MB",
  },
];
