export const ANUAL_EVALUATION_LIST_REQUEST = "ANUAL_EVALUATION_LIST_REQUEST";
export const ANUAL_EVALUATION_LIST_SUCCESS = "ANUAL_EVALUATION_LIST_SUCCESS";
export const ANUAL_EVALUATION_LIST_ERROR = "ANUAL_EVALUATION_LIST_ERROR";
export const ANUAL_EVALUATION_LIST_RESET = "ANUAL_EVALUATION_LIST_RESET";

export const ANUAL_EVALUATION_ADD_REQUEST = "ANUAL_EVALUATION_ADD_REQUEST";
export const ANUAL_EVALUATION_ADD_SUCCESS = "ANUAL_EVALUATION_ADD_SUCCESS";
export const ANUAL_EVALUATION_ADD_ERROR = "ANUAL_EVALUATION_ADD_ERROR";
export const ANUAL_EVALUATION_ADD_RESET = "ANUAL_EVALUATION_ADD_RESET";

export const ANUAL_EVALUATION_DETAILS_REQUEST = "ANUAL_EVALUATION_DETAILS_REQUEST";
export const ANUAL_EVALUATION_DETAILS_SUCCESS = "ANUAL_EVALUATION_DETAILS_SUCCESS";
export const ANUAL_EVALUATION_DETAILS_ERROR = "ANUAL_EVALUATION_DETAILS_ERROR";
export const ANUAL_EVALUATION_DETAILS_RESET = "ANUAL_EVALUATION_DETAILS_RESET";

export const ANUAL_EVALUATION_EDIT_REQUEST = "ANUAL_EVALUATION_EDIT_REQUEST";
export const ANUAL_EVALUATION_EDIT_SUCCESS = "ANUAL_EVALUATION_EDIT_SUCCESS";
export const ANUAL_EVALUATION_EDIT_ERROR = "ANUAL_EVALUATION_EDIT_ERROR";
export const ANUAL_EVALUATION_EDIT_RESET = "ANUAL_EVALUATION_EDIT_RESET";
