export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";
export const CATEGORY_LIST_RESET = "CATEGORY_LIST_RESET";

export const CATEGORY_SINCRO_REQUEST = "CATEGORY_SINCRO_REQUEST";
export const CATEGORY_SINCRO_SUCCESS = "CATEGORY_SINCRO_SUCCESS";
export const CATEGORY_SINCRO_ERROR = "CATEGORY_SINCRO_ERROR";
export const CATEGORY_SINCRO_RESET = "CATEGORY_SINCRO_RESET";

export const CATEGORY_REBUILD_LIST_REQUEST = "CATEGORY_REBUILD_LIST_REQUEST";
export const CATEGORY_REBUILD_LIST_SUCCESS = "CATEGORY_REBUILD_LIST_SUCCESS";
export const CATEGORY_REBUILD_LIST_ERROR = "CATEGORY_REBUILD_LIST_ERROR";
export const CATEGORY_REBUILD_LIST_RESET = "CATEGORY_REBUILD_LIST_RESET";
