export const CHARGE_LIST_REQUEST = 'CHARGE_LIST_REQUEST';
export const CHARGE_LIST_SUCCESS = 'CHARGE_LIST_SUCCESS';
export const CHARGE_LIST_ERROR = 'CHARGE_LIST_ERROR';
export const CHARGE_LIST_RESET = 'CHARGE_LIST_RESET';

export const CHARGE_LIST_ZUNPR_REQUEST = 'CHARGE_LIST_ZUNPR_REQUEST';
export const CHARGE_LIST_ZUNPR_SUCCESS = 'CHARGE_LIST_ZUNPR_SUCCESS';
export const CHARGE_LIST_ZUNPR_ERROR = 'CHARGE_LIST_ZUNPR_ERROR';
export const CHARGE_LIST_ZUNPR_RESET = 'CHARGE_LIST_ZUNPR_RESET';

export const CHARGE_LIST_REBUILD_REQUEST = 'CHARGE_LIST_REBUILD_REQUEST';
export const CHARGE_LIST_REBUILD_SUCCESS = 'CHARGE_LIST_REBUILD_SUCCESS';
export const CHARGE_LIST_REBUILD_ERROR = 'CHARGE_LIST_REBUILD_ERROR';
export const CHARGE_LIST_REBUILD_RESET = 'CHARGE_LIST_REBUILD_RESET';