export const COIN_LIST_REQUEST = "COIN_LIST_REQUEST";
export const COIN_LIST_SUCCESS = "COIN_LIST_SUCCESS";
export const COIN_LIST_ERROR = "COIN_LIST_ERROR";
export const COIN_LIST_RESET = "COIN_LIST_RESET";

export const GET_COIN_REQUEST = "GET_COIN_REQUEST";
export const GET_COIN_SUCCESS = "GET_COIN_SUCCESS";
export const GET_COIN_ERROR = "GET_COIN_ERROR";
export const GET_COIN_RESET = "GET_COIN_RESET";

export const COIN_LIST_FROM_PMS_REQUEST = "COIN_LIST_FROM_PMS_REQUEST";
export const COIN_LIST_FROM_PMS_SUCCESS = "COIN_LIST_FROM_PMS_SUCCESS";
export const COIN_LIST_FROM_PMS_ERROR = "COIN_LIST_FROM_PMS_ERROR";
export const COIN_LIST_FROM_PMS_RESET = "COIN_LIST_FROM_PMS_RESET";


export const COIN_LIST_REBUILD_REQUEST = "COIN_LIST_REBUILD_REQUEST";
export const COIN_LIST_REBUILD_SUCCESS = "COIN_LIST_REBUILD_SUCCESS";
export const COIN_LIST_REBUILD_ERROR = "COIN_LIST_REBUILD_ERROR";
export const COIN_LIST_REBUILD_RESET = "COIN_LIST_REBUILD_RESET";
