export const NUMBERS = {
  GET_DATA: "GET_DATA",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_ERROR: "DATA_ERROR",
  DATA_RESET: "DATA_RESET",
};

export const RANGE_EVALUATION = {
  GET_EVALUATIONS_RANGE: "GET_EVALUATIONS_RANGE",
  EVALUATIONS_RANGE_SUCCESS: "EVALUATIONS_RANGE_SUCCESS",
  EVALUATIONS_RANGE_ERROR: "EVALUATIONS_RANGE_ERROR",
  EVALUATIONS_RANGE_RESET: "EVALUATIONS_RANGE_RESET",
};

export const ANUAL_EVALUATION = {
  GET_EVALUATIONS_RANGE: "GET_ANUAL_EVALUATIONS_RANGE",
  EVALUATIONS_RANGE_SUCCESS: "EVALUATIONS_ANUAL_RANGE_SUCCESS",
  EVALUATIONS_RANGE_ERROR: "EVALUATIONS_ANUAL_RANGE_ERROR",
  EVALUATIONS_RANGE_RESET: "EVALUATIONS_ANUAL_RANGE_RESET",
};
