export const FAMILY_LIST_REQUEST = 'FAMILY_LIST_REQUEST';
export const FAMILY_LIST_SUCCESS = 'FAMILY_LIST_SUCCESS';
export const FAMILY_LIST_ERROR = 'FAMILY_LIST_ERROR';
export const FAMILY_LIST_RESET = 'FAMILY_LIST_RESET';

export const FAMILY_LIST_FROM_ZUNPOS_REQUEST = 'FAMILY_LIST_FROM_ZUNPOS_REQUEST';
export const FAMILY_LIST_FROM_ZUNPOS_SUCCESS = 'FAMILY_LIST_FROM_ZUNPOS_SUCCESS';
export const FAMILY_LIST_FROM_ZUNPOS_ERROR = 'FAMILY_LIST_FROM_ZUNPOS_ERROR';
export const FAMILY_LIST_FROM_ZUNPOS_RESET = 'FAMILY_LIST_FROM_ZUNPOS_RESET';

export const FAMILY_LIST_UPDATE_FROM_ZUNPOS_REQUEST = 'FAMILY_LIST_UPDATE_FROM_ZUNPOS_REQUEST';
export const FAMILY_LIST_UPDATE_FROM_ZUNPOS_SUCCESS = 'FAMILY_LIST_UPDATE_FROM_ZUNPOS_SUCCESS';
export const FAMILY_LIST_UPDATE_FROM_ZUNPOS_ERROR = 'FAMILY_LIST_UPDATE_FROM_ZUNPOS_ERROR';
export const FAMILY_LIST_UPDATE_FROM_ZUNPOS_RESET = 'FAMILY_LIST_UPDATE_FROM_ZUNPOS_RESET';

export const FAMILY_DELETE_REQUEST = 'FAMILY_DELETE_REQUEST';
export const FAMILY_DELETE_SUCCESS = 'FAMILY_DELETE_SUCCESS';
export const FAMILY_DELETE_ERROR = 'FAMILY_DELETE_ERROR';
export const FAMILY_DELETE_RESET = 'FAMILY_DELETE_RESET';

export const FAMILY_SINCRONIZE_REQUEST = 'FAMILY_SINCRONIZE_REQUEST';
export const FAMILY_SINCRONIZE_SUCCESS = 'FAMILY_SINCRONIZE_SUCCESS';
export const FAMILY_SINCRONIZE_ERROR = 'FAMILY_SINCRONIZE_ERROR';
export const FAMILY_SINCRONIZE_RESET = 'FAMILY_SINCRONIZE_RESET';