export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';
export const HOTEL_LIST_RESET = 'HOTEL_LIST_RESET';

export const HOTEL_ADD_REQUEST = 'HOTEL_ADD_REQUEST';
export const HOTEL_ADD_SUCCESS = 'HOTEL_ADD_SUCCESS';
export const HOTEL_ADD_FAIL = 'HOTEL_ADD_FAIL';
export const HOTEL_ADD_RESET = 'HOTEL_ADD_RESET';

export const HOTEL_DELETE_REQUEST = 'HOTEL_DELETE_REQUEST';
export const HOTEL_DELETE_SUCCESS = 'HOTEL_DELETE_SUCCESS';
export const HOTEL_DELETE_FAIL = 'HOTEL_DELETE_FAIL';
export const HOTEL_DELETE_RESET = 'HOTEL_DELETE_RESET';

export const HOTEL_DETAILS_REQUEST = 'HOTEL_DETAILS_REQUEST';
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS';
export const HOTEL_DETAILS_FAIL = 'HOTEL_DETAILS_FAIL';
export const HOTEL_DETAILS_RESET = 'HOTEL_DETAILS_RESET';

export const HOTEL_EDIT_REQUEST = 'HOTEL_EDIT_REQUEST';
export const HOTEL_EDIT_SUCCESS = 'HOTEL_EDIT_SUCCESS';
export const HOTEL_EDIT_FAIL = 'HOTEL_EDIT_FAIL';
export const HOTEL_EDIT_RESET = 'HOTEL_EDIT_RESET';