export const MONTHLY_SALE_PLAN_LIST_REQUEST = 'MONTHLY_SALE_PLAN_LIST_REQUEST';
export const MONTHLY_SALE_PLAN_LIST_SUCCESS = 'MONTHLY_SALE_PLAN_LIST_SUCCESS';
export const MONTHLY_SALE_PLAN_LIST_ERROR = 'MONTHLY_SALE_PLAN_LIST_ERROR';
export const MONTHLY_SALE_PLAN_LIST_RESET = 'MONTHLY_SALE_PLAN_LIST_RESET';

export const MONTHLY_SALE_PLAN_DELETE_REQUEST = 'MONTHLY_SALE_PLAN_DELETE_REQUEST';
export const MONTHLY_SALE_PLAN_DELETE_SUCCESS = 'MONTHLY_SALE_PLAN_DELETE_SUCCESS';
export const MONTHLY_SALE_PLAN_DELETE_ERROR = 'MONTHLY_SALE_PLAN_DELETE_ERROR';
export const MONTHLY_SALE_PLAN_DELETE_RESET = 'MONTHLY_SALE_PLAN_DELETE_RESET';

export const MONTHLY_SALE_PLAN_EDIT_REQUEST = 'MONTHLY_SALE_PLAN_EDIT_REQUEST';
export const MONTHLY_SALE_PLAN_EDIT_SUCCESS = 'MONTHLY_SALE_PLAN_EDIT_SUCCESS';
export const MONTHLY_SALE_PLAN_EDIT_ERROR = 'MONTHLY_SALE_PLAN_EDIT_ERROR';
export const MONTHLY_SALE_PLAN_EDIT_RESET = 'MONTHLY_SALE_PLAN_EDIT_RESET';

export const MONTHLY_SALE_PLAN_DETAILS_REQUEST = 'MONTHLY_SALE_PLAN_DETAILS_REQUEST';
export const MONTHLY_SALE_PLAN_DETAILS_SUCCESS = 'MONTHLY_SALE_PLAN_DETAILS_SUCCESS';
export const MONTHLY_SALE_PLAN_DETAILS_ERROR = 'MONTHLY_SALE_PLAN_DETAILS_ERROR';
export const MONTHLY_SALE_PLAN_DETAILS_RESET = 'MONTHLY_SALE_PLAN_DETAILS_RESET';

export const MONTHLY_SALE_PLAN_CREATE_REQUEST = 'MONTHLY_SALE_PLAN_CREATE_REQUEST';
export const MONTHLY_SALE_PLAN_CREATE_SUCCESS = 'MONTHLY_SALE_PLAN_CREATE_SUCCESS';
export const MONTHLY_SALE_PLAN_CREATE_ERROR = 'MONTHLY_SALE_PLAN_CREATE_ERROR';
export const MONTHLY_SALE_PLAN_CREATE_RESET = 'MONTHLY_SALE_PLAN_CREATE_RESET';
