export const WORKER_MONTHLY_EVALUATION_LIST_REQUEST = 'WORKER_MONTHLY_EVALUATION_LIST_REQUEST'; 
export const WORKER_MONTHLY_EVALUATION_LIST_SUCCESS = 'WORKER_MONTHLY_EVALUATION_LIST_SUCCESS'; 
export const WORKER_MONTHLY_EVALUATION_LIST_ERROR = 'WORKER_MONTHLY_EVALUATION_LIST_ERROR'; 
export const WORKER_MONTHLY_EVALUATION_LIST_RESET = 'WORKER_MONTHLY_EVALUATION_LIST_RESET'; 

export const WORKER_MONTHLY_EVALUATION_ADD_REQUEST = 'WORKER_MONTHLY_EVALUATION_ADD_REQUEST'; 
export const WORKER_MONTHLY_EVALUATION_ADD_SUCCESS = 'WORKER_MONTHLY_EVALUATION_ADD_SUCCESS'; 
export const WORKER_MONTHLY_EVALUATION_ADD_ERROR = 'WORKER_MONTHLY_EVALUATION_ADD_ERROR'; 
export const WORKER_MONTHLY_EVALUATION_ADD_RESET = 'WORKER_MONTHLY_EVALUATION_ADD_RESET'; 

export const WORKER_MONTHLY_EVALUATION_EDIT_REQUEST = 'WORKER_MONTHLY_EVALUATION_EDIT_REQUEST'; 
export const WORKER_MONTHLY_EVALUATION_EDIT_SUCCESS = 'WORKER_MONTHLY_EVALUATION_EDIT_SUCCESS'; 
export const WORKER_MONTHLY_EVALUATION_EDIT_ERROR = 'WORKER_MONTHLY_EVALUATION_EDIT_ERROR'; 
export const WORKER_MONTHLY_EVALUATION_EDIT_RESET = 'WORKER_MONTHLY_EVALUATION_EDIT_RESET'; 

export const WORKER_MONTHLY_EVALUATION_DETAILS_REQUEST = 'WORKER_MONTHLY_EVALUATION_DETAILS_REQUEST'; 
export const WORKER_MONTHLY_EVALUATION_DETAILS_SUCCESS = 'WORKER_MONTHLY_EVALUATION_DETAILS_SUCCESS'; 
export const WORKER_MONTHLY_EVALUATION_DETAILS_ERROR = 'WORKER_MONTHLY_EVALUATION_DETAILS_ERROR'; 
export const WORKER_MONTHLY_EVALUATION_DETAILS_RESET = 'WORKER_MONTHLY_EVALUATION_DETAILS_RESET'; 

export const MONTHLY_MELIA_EVALUATION_ADD_REQUEST = 'MONTHLY_MELIA_EVALUATION_ADD_REQUEST'; 
export const MONTHLY_MELIA_EVALUATION_ADD_SUCCESS = 'MONTHLY_MELIA_EVALUATION_ADD_SUCCESS'; 
export const MONTHLY_MELIA_EVALUATION_ADD_ERROR = 'MONTHLY_MELIA_EVALUATION_ADD_ERROR'; 
export const MONTHLY_MELIA_EVALUATION_ADD_RESET = 'MONTHLY_MELIA_EVALUATION_ADD_RESET'; 

export const MONTHLY_MELIA_EVALUATION_DETAILS_REQUEST = 'MONTHLY_MELIA_EVALUATION_DETAILS_REQUEST'; 
export const MONTHLY_MELIA_EVALUATION_DETAILS_SUCCESS = 'MONTHLY_MELIA_EVALUATION_DETAILS_SUCCESS'; 
export const MONTHLY_MELIA_EVALUATION_DETAILS_ERROR = 'MONTHLY_MELIA_EVALUATION_DETAILS_ERROR'; 
export const MONTHLY_MELIA_EVALUATION_DETAILS_RESET = 'MONTHLY_MELIA_EVALUATION_DETAILS_RESET'; 

export const MONTHLY_MELIA_EVALUATION_EDIT_REQUEST = 'MONTHLY_MELIA_EVALUATION_EDIT_REQUEST'; 
export const MONTHLY_MELIA_EVALUATION_EDIT_SUCCESS = 'MONTHLY_MELIA_EVALUATION_EDIT_SUCCESS'; 
export const MONTHLY_MELIA_EVALUATION_EDIT_ERROR = 'MONTHLY_MELIA_EVALUATION_EDIT_ERROR'; 
export const MONTHLY_MELIA_EVALUATION_EDIT_RESET = 'MONTHLY_MELIA_EVALUATION_EDIT_RESET'; 

export const MONTHLY_MELIA_EVALUATION_RESUME_REQUEST = 'MONTHLY_MELIA_EVALUATION_RESUME_REQUEST'; 
export const MONTHLY_MELIA_EVALUATION_RESUME_SUCCESS = 'MONTHLY_MELIA_EVALUATION_RESUME_SUCCESS'; 
export const MONTHLY_MELIA_EVALUATION_RESUME_ERROR = 'MONTHLY_MELIA_EVALUATION_RESUME_ERROR'; 
export const MONTHLY_MELIA_EVALUATION_RESUME_RESET = 'MONTHLY_MELIA_EVALUATION_RESUME_RESET'; 
