export const PAYTIMES_LIST_REQUEST = 'PAYTIMES_LIST_REQUEST';
export const PAYTIMES_LIST_SUCCESS = 'PAYTIMES_LIST_SUCCESS';
export const PAYTIMES_LIST_ERROR = 'PAYTIMES_LIST_ERROR';
export const PAYTIMES_LIST_RESET = 'PAYTIMES_LIST_RESET';

export const PAYTIMES_IMPORT_REQUEST = 'PAYTIMES_IMPORT_REQUEST';
export const PAYTIMES_IMPORT_SUCCESS = 'PAYTIMES_IMPORT_SUCCESS';
export const PAYTIMES_IMPORT_ERROR = 'PAYTIMES_IMPORT_ERROR';
export const PAYTIMES_IMPORT_RESET = 'PAYTIMES_IMPORT_RESET';

export const PAYTIMES_SINCRO_REQUEST = 'PAYTIMES_SINCRO_REQUEST';
export const PAYTIMES_SINCRO_SUCCESS = 'PAYTIMES_SINCRO_SUCCESS';
export const PAYTIMES_SINCRO_ERROR = 'PAYTIMES_SINCRO_ERROR';
export const PAYTIMES_SINCRO_RESET = 'PAYTIMES_SINCRO_RESET';

export const PAYTIMES_ZUN_LIST_REQUEST = 'PAYTIMES_ZUN_LIST_REQUEST';
export const PAYTIMES_ZUN_LIST_SUCCESS = 'PAYTIMES_ZUN_LIST_SUCCESS';
export const PAYTIMES_ZUN_LIST_ERROR = 'PAYTIMES_ZUN_LIST_ERROR';
export const PAYTIMES_ZUN_LIST_RESET = 'PAYTIMES_ZUN_LIST_RESET';

export const PAYTIMES_DELETE_REQUEST = 'PAYTIMES_DELETE_REQUEST';
export const PAYTIMES_DELETE_SUCCESS = 'PAYTIMES_DELETE_SUCCESS';
export const PAYTIMES_DELETE_ERROR = 'PAYTIMES_DELETE_ERROR';
export const PAYTIMES_DELETE_RESET = 'PAYTIMES_DELETE_RESET';

export const PAYTIMES_REBUILD_REQUEST = 'PAYTIMES_REBUILD_REQUEST';
export const PAYTIMES_REBUILD_SUCCESS = 'PAYTIMES_REBUILD_SUCCESS';
export const PAYTIMES_REBUILD_ERROR = 'PAYTIMES_REBUILD_ERROR';
export const PAYTIMES_REBUILD_RESET = 'PAYTIMES_REBUILD_RESET';

export const PAYTIMES_DETAILS_REQUEST = 'PAYTIMES_DETAILS_REQUEST';
export const PAYTIMES_DETAILS_SUCCESS = 'PAYTIMES_DETAILS_SUCCESS';
export const PAYTIMES_DETAILS_ERROR = 'PAYTIMES_DETAILS_ERROR';
export const PAYTIMES_DETAILS_RESET = 'PAYTIMES_DETAILS_RESET';