export const SELL_AREA_LIST_REQUEST = 'SELL_AREA_LIST_REQUEST';
export const SELL_AREA_LIST_SUCCESS = 'SELL_AREA_LIST_SUCCESS';
export const SELL_AREA_LIST_ERROR = 'SELL_AREA_LIST_ERROR';
export const SELL_AREA_LIST_RESET = 'SELL_AREA_LIST_RESET';

export const SELL_AREA_LIST_FROM_ZUNPOS_REQUEST = 'SELL_AREA_LIST_FROM_ZUNPOS_REQUEST';
export const SELL_AREA_LIST_FROM_ZUNPOS_SUCCESS = 'SELL_AREA_LIST_FROM_ZUNPOS_SUCCESS';
export const SELL_AREA_LIST_FROM_ZUNPOS_ERROR = 'SELL_AREA_LIST_FROM_ZUNPOS_ERROR';
export const SELL_AREA_LIST_FROM_ZUNPOS_RESET = 'SELL_AREA_LIST_FROM_ZUNPOS_RESET';

export const SELL_AREA_UPDATE_REQUEST = 'SELL_AREA_UPDATE_REQUEST';
export const SELL_AREA_UPDATE_SUCCESS = 'SELL_AREA_UPDATE_SUCCESS';
export const SELL_AREA_UPDATE_ERROR = 'SELL_AREA_UPDATE_ERROR';
export const SELL_AREA_UPDATE_RESET = 'SELL_AREA_UPDATE_RESET';

export const SELL_AREA_DELETE_REQUEST = 'SELL_AREA_DELETE_REQUEST';
export const SELL_AREA_DELETE_SUCCESS = 'SELL_AREA_DELETE_SUCCESS';
export const SELL_AREA_DELETE_ERROR = 'SELL_AREA_DELETE_ERROR';
export const SELL_AREA_DELETE_RESET = 'SELL_AREA_DELETE_RESET';

export const SELL_AREA_SINCRONIZE_REQUEST = 'SELL_AREA_SINCRONIZE_REQUEST';
export const SELL_AREA_SINCRONIZE_SUCCESS = 'SELL_AREA_SINCRONIZE_SUCCESS';
export const SELL_AREA_SINCRONIZE_ERROR = 'SELL_AREA_SINCRONIZE_ERROR';
export const SELL_AREA_SINCRONIZE_RESET = 'SELL_AREA_SINCRONIZE_RESET';

export const SELL_AREA_REBUILD_LIST_REQUEST = 'SELL_AREA_REBUILD_LIST_REQUEST';
export const SELL_AREA_REBUILD_LIST_SUCCESS = 'SELL_AREA_REBUILD_LIST_SUCCESS';
export const SELL_AREA_REBUILD_LIST_ERROR = 'SELL_AREA_REBUILD_LIST_ERROR';
export const SELL_AREA_REBUILD_LIST_RESET = 'SELL_AREA_REBUILD_LIST_RESET';