export const OPERATOR_LIST_REQUEST = 'OPERATOR_LIST_REQUEST'; 
export const OPERATOR_LIST_SUCCESS = 'OPERATOR_LIST_SUCCESS'; 
export const OPERATOR_LIST_ERROR = 'OPERATOR_LIST_ERROR'; 
export const OPERATOR_LIST_RESET = 'OPERATOR_LIST_RESET'; 

export const OPERATOR_DELETE_REQUEST = 'OPERATOR_DELETE_REQUEST'; 
export const OPERATOR_DELETE_SUCCESS = 'OPERATOR_DELETE_SUCCESS'; 
export const OPERATOR_DELETE_ERROR = 'OPERATOR_DELETE_ERROR'; 
export const OPERATOR_DELETE_RESET = 'OPERATOR_DELETE_RESET'; 

export const SET_OPERATOR_REQUEST = 'SET_OPERATOR_REQUEST'; 
export const SET_OPERATOR_SUCCESS = 'SET_OPERATOR_SUCCESS'; 
export const SET_OPERATOR_ERROR = 'SET_OPERATOR_ERROR'; 
export const SET_OPERATOR_RESET = 'SET_OPERATOR_RESET'; 

export const WORKER_LIST_REQUEST = 'WORKER_LIST_REQUEST'; 
export const WORKER_LIST_SUCCESS = 'WORKER_LIST_SUCCESS'; 
export const WORKER_LIST_ERROR = 'WORKER_LIST_ERROR'; 
export const WORKER_LIST_RESET = 'WORKER_LIST_RESET'; 

export const WORKER_DELETE_REQUEST = 'WORKER_DELETE_REQUEST'; 
export const WORKER_DELETE_SUCCESS = 'WORKER_DELETE_SUCCESS'; 
export const WORKER_DELETE_ERROR = 'WORKER_DELETE_ERROR'; 
export const WORKER_DELETE_RESET = 'WORKER_DELETE_RESET'; 

export const WORKER_LIST_FROM_ZUNPR_REQUEST = 'WORKER_LIST_FROM_ZUNPR_REQUEST'; 
export const WORKER_LIST_FROM_ZUNPR_SUCCESS = 'WORKER_LIST_FROM_ZUNPR_SUCCESS'; 
export const WORKER_LIST_FROM_ZUNPR_ERROR = 'WORKER_LIST_FROM_ZUNPR_ERROR'; 
export const WORKER_LIST_FROM_ZUNPR_RESET = 'WORKER_LIST_FROM_ZUNPR_RESET'; 

export const WORKER_IMPORT_FROM_ZUNPR_REQUEST = 'WORKER_IMPORT_FROM_ZUNPR_REQUEST'; 
export const WORKER_IMPORT_FROM_ZUNPR_SUCCESS = 'WORKER_IMPORT_FROM_ZUNPR_SUCCESS'; 
export const WORKER_IMPORT_FROM_ZUNPR_ERROR = 'WORKER_IMPORT_FROM_ZUNPR_ERROR'; 
export const WORKER_IMPORT_FROM_ZUNPR_RESET = 'WORKER_IMPORT_FROM_ZUNPR_RESET'; 

export const WORKER_SINCRO_REQUEST = 'WORKER_SINCRO_REQUEST'; 
export const WORKER_SINCRO_SUCCESS = 'WORKER_SINCRO_SUCCESS'; 
export const WORKER_SINCRO_ERROR = 'WORKER_SINCRO_ERROR'; 
export const WORKER_SINCRO_RESET = 'WORKER_SINCRO_RESET'; 

export const WORKER_REBUILD_REQUEST = 'WORKER_REBUILD_REQUEST'; 
export const WORKER_REBUILD_SUCCESS = 'WORKER_REBUILD_SUCCESS'; 
export const WORKER_REBUILD_ERROR = 'WORKER_REBUILD_ERROR'; 
export const WORKER_REBUILD_RESET = 'WORKER_REBUILD_RESET'; 

export const WORKER_DETAILS_REQUEST = 'WORKER_DETAILS_REQUEST'; 
export const WORKER_DETAILS_SUCCESS = 'WORKER_DETAILS_SUCCESS'; 
export const WORKER_DETAILS_ERROR = 'WORKER_DETAILS_ERROR'; 
export const WORKER_DETAILS_RESET = 'WORKER_DETAILS_RESET'; 

export const WORKER_EVALUATOR_DETAILS_REQUEST = 'WORKER_EVALUATOR_DETAILS_REQUEST'; 
export const WORKER_EVALUATOR_DETAILS_SUCCESS = 'WORKER_EVALUATOR_DETAILS_SUCCESS'; 
export const WORKER_EVALUATOR_DETAILS_ERROR = 'WORKER_EVALUATOR_DETAILS_ERROR'; 
export const WORKER_EVALUATOR_DETAILS_RESET = 'WORKER_EVALUATOR_DETAILS_RESET'; 
